trigger:
- main

pr:
- '*'

pool:
  vmImage: ubuntu-latest
variables:
  - group: Pipeline_Variables

steps:
- script: echo Magic Happening!!!
  displayName: 'Connecting...Wait for the Magic!!!'

- script: |
    echo "Logging in via service principal - putting the agent to work ."
  displayName: 'Agent Going to Work'

- script: |
    echo "Initializing Terraform..."
    # Run Terraform commands to create and manage your infrastructure.
    az login --service-principal --username CLIENT_ID --password CLIENT_SECRET --tenant TENANT_ID
    terraform init
  displayName: 'Initializing Terraform'

- script: |
    echo "Terraform Plan..."
    terraform plan -out=terraform.plan
  displayName: 'Terraform Plan'

- script: |
    echo "Building infrastructure with Terraform..."
    terraform apply "terraform.plan"
  displayName: 'Build Infrastructure with Terraform'